name: irctc-backend

services:
  postgres:
    image: postgres:18
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: irctcadmin
      POSTGRES_DB: postgres
    ports:
      - "5400:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./docker/postgres/init-service-databases.sql:/docker-entrypoint-initdb.d/01-create-service-databases.sql:ro
      - ./tests/postgres/init-test-database.sql:/docker-entrypoint-initdb.d/02-create-test-database.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:9.8
    container_name: pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"

  redis:
    image: redis/redis-stack:7.4.0-v8
    container_name: redis
    restart: always
    environment:
      REDIS_ARGS: "--requirepass irctcadmin"
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
