syntax = "proto3";

package user.v1;

import "user/v1/user.proto";

option go_package = "github.com/JustUzair/go-grpc-irctc-backend/gen/go/user/v1;userv1";

service UserService {
  rpc GetUser(GetUserRequest) returns (GetUserResponse);
  rpc SendOTP(SendOTPRequest) returns (SendOTPResponse);
  rpc VerifyOTP(VerifyOTPRequest) returns (VerifyOTPResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
}

// ####### RPC SendOTP  #######

message SendOTPRequest {
  string first_name = 1;
  string last_name = 2;
  string email = 3;
  string password = 4;
  string confirm_password = 5;
}
message SendOTPResponse {
  bool status = 1;
  string message = 2;
  string otp_session_id = 3;
}

// ####### RPC Login  #######

message LoginRequest {
  string email = 1;
  string password = 2;
}
message LoginResponse {
  string access_token = 1;
  string refresh_token = 2;
  User user = 3;
  int64 access_token_expires_in = 4;
  int64 refresh_token_expires_in = 5;
}
// ####### RPC VerifyOTP  #######
message VerifyOTPRequest {
  string otp = 1;
  string otp_session_id = 2;
}
message VerifyOTPResponse {
  User user = 1;
  bool success = 2;
  string status_message = 3;
}

// ####### RPC GetUser  #######
message GetUserRequest {}

message GetUserResponse {
  User user = 1;
}
